{ pkgs }:
let
  fftwLibraryName = "libfftw3${pkgs.stdenv.hostPlatform.extensions.sharedLibrary}";
in
# FFTW's Autotools install omits the imported CMake target generated by its
# CMake build. Supply equivalent metadata until upstream FFTW/Nixpkgs provides
# FFTW3::fftw3 natively for this package path.
pkgs.fftw.overrideAttrs (oldAttrs: {
  postInstall = (oldAttrs.postInstall or "") + ''
    substitute ${./FFTW3LibraryDepends.cmake.in} \
      "$out/lib/cmake/fftw3/FFTW3LibraryDepends.cmake" \
      --subst-var out \
      --subst-var dev \
      --subst-var-by fftwLibraryName ${fftwLibraryName}
  '';
})
